substitutions:
  my_ssid: !secret wifi_ssid
  my_password: !secret wifi_password

esphome:
  name: ${node_name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: huzzah

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Default logging level
logger:
  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO

status_led:
  pin:
    number: GPIO2
    inverted: true

wifi:
  ssid: "${my_ssid}"
  password: "${my_password}"
  min_auth_mode: WPA2

# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

sensor:
  - platform: uptime
    name: Uptime

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: None
    icon: mdi:air-conditioner
    visual:
      min_temperature: 13 # Adjust to your unit's min temp. SmartSet units can go to 10C for heating
      max_temperature: 33
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    fahrenheit_compatibility: true
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    update_interval: 5s
    debounce_delay : 100ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: false
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: true
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: false
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: true
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: false
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    input_power_sensor:
      name: Input Power
      disabled_by_default: false
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: false
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: false
